### ISSUE TITLE
Deserializing a representation with schema from a Array[Byte] fails

### ISSUE THREAD

**Issue by tonicebrian** [sksamuel/sbt-avro4s#12]
I was trying to read from a Kafka Topic works flawless when not sending the schema, but I was trying to read binary representations including a schema by using `AvroInputStream.data(bytes : Array[Bytes])` and it fails with the following exception:

        java.io.IOException: Not a data file.
        at org.apache.avro.file.DataFileStream.initialize(DataFileStream.java:105)
        at org.apache.avro.file.DataFileReader.<init>(DataFileReader.java:97)
        at com.sksamuel.avro4s.AvroDataInputStream.<init>(AvroInputStream.scala:52)
        at com.sksamuel.avro4s.AvroInputStream$.data(AvroInputStream.scala:104)

Maybe I'm doing something wrong but is it a bug? or how should I read from an `Array[Byte]` a serialization containing a schema?

**Comment by sksamuel** [comment]
You can use the `AvroInputStream.binary` variant.
